// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Photo.proto

package com.orange.network.game.protocol.model;

public final class PhotoProtos {
  private PhotoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum PBPhotoUsage
      implements com.google.protobuf.ProtocolMessageEnum {
    BEGIN(0, 0),
    FOR_DRAW(1, 1),
    FOR_PS(2, 2),
    END(3, 3),
    ;
    
    public static final int BEGIN_VALUE = 0;
    public static final int FOR_DRAW_VALUE = 1;
    public static final int FOR_PS_VALUE = 2;
    public static final int END_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static PBPhotoUsage valueOf(int value) {
      switch (value) {
        case 0: return BEGIN;
        case 1: return FOR_DRAW;
        case 2: return FOR_PS;
        case 3: return END;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<PBPhotoUsage>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PBPhotoUsage>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBPhotoUsage>() {
            public PBPhotoUsage findValueByNumber(int number) {
              return PBPhotoUsage.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.PhotoProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final PBPhotoUsage[] VALUES = {
      BEGIN, FOR_DRAW, FOR_PS, END, 
    };
    
    public static PBPhotoUsage valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private PBPhotoUsage(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:game.PBPhotoUsage)
  }
  
  public interface PBUserPhotoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string userId = 1;
    boolean hasUserId();
    String getUserId();
    
    // optional string photoId = 2;
    boolean hasPhotoId();
    String getPhotoId();
    
    // optional string userPhotoId = 3;
    boolean hasUserPhotoId();
    String getUserPhotoId();
    
    // required string url = 4;
    boolean hasUrl();
    String getUrl();
    
    // optional string name = 5;
    boolean hasName();
    String getName();
    
    // optional int32 createDate = 6;
    boolean hasCreateDate();
    int getCreateDate();
    
    // repeated string tags = 7;
    java.util.List<String> getTagsList();
    int getTagsCount();
    String getTags(int index);
    
    // optional int32 usage = 8;
    boolean hasUsage();
    int getUsage();
    
    // optional float width = 9;
    boolean hasWidth();
    float getWidth();
    
    // optional float height = 10;
    boolean hasHeight();
    float getHeight();
  }
  public static final class PBUserPhoto extends
      com.google.protobuf.GeneratedMessage
      implements PBUserPhotoOrBuilder {
    // Use PBUserPhoto.newBuilder() to construct.
    private PBUserPhoto(Builder builder) {
      super(builder);
    }
    private PBUserPhoto(boolean noInit) {}
    
    private static final PBUserPhoto defaultInstance;
    public static PBUserPhoto getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBUserPhoto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.PhotoProtos.internal_static_game_PBUserPhoto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.model.PhotoProtos.internal_static_game_PBUserPhoto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string photoId = 2;
    public static final int PHOTOID_FIELD_NUMBER = 2;
    private java.lang.Object photoId_;
    public boolean hasPhotoId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPhotoId() {
      java.lang.Object ref = photoId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          photoId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhotoIdBytes() {
      java.lang.Object ref = photoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        photoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string userPhotoId = 3;
    public static final int USERPHOTOID_FIELD_NUMBER = 3;
    private java.lang.Object userPhotoId_;
    public boolean hasUserPhotoId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getUserPhotoId() {
      java.lang.Object ref = userPhotoId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userPhotoId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserPhotoIdBytes() {
      java.lang.Object ref = userPhotoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userPhotoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string url = 4;
    public static final int URL_FIELD_NUMBER = 4;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 createDate = 6;
    public static final int CREATEDATE_FIELD_NUMBER = 6;
    private int createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getCreateDate() {
      return createDate_;
    }
    
    // repeated string tags = 7;
    public static final int TAGS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList tags_;
    public java.util.List<String>
        getTagsList() {
      return tags_;
    }
    public int getTagsCount() {
      return tags_.size();
    }
    public String getTags(int index) {
      return tags_.get(index);
    }
    
    // optional int32 usage = 8;
    public static final int USAGE_FIELD_NUMBER = 8;
    private int usage_;
    public boolean hasUsage() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getUsage() {
      return usage_;
    }
    
    // optional float width = 9;
    public static final int WIDTH_FIELD_NUMBER = 9;
    private float width_;
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public float getWidth() {
      return width_;
    }
    
    // optional float height = 10;
    public static final int HEIGHT_FIELD_NUMBER = 10;
    private float height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public float getHeight() {
      return height_;
    }
    
    private void initFields() {
      userId_ = "";
      photoId_ = "";
      userPhotoId_ = "";
      url_ = "";
      name_ = "";
      createDate_ = 0;
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      usage_ = 0;
      width_ = 0F;
      height_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPhotoIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserPhotoIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, createDate_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        output.writeBytes(7, tags_.getByteString(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(8, usage_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(9, width_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(10, height_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPhotoIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserPhotoIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, createDate_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tags_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(tags_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, usage_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, width_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, height_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.model.PhotoProtos.internal_static_game_PBUserPhoto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.model.PhotoProtos.internal_static_game_PBUserPhoto_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        photoId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userPhotoId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        createDate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        usage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        width_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        height_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.getDescriptor();
      }
      
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto getDefaultInstanceForType() {
        return com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto build() {
        com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto buildPartial() {
        com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto result = new com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.photoId_ = photoId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userPhotoId_ = userPhotoId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.createDate_ = createDate_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          tags_ = new com.google.protobuf.UnmodifiableLazyStringList(
              tags_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.tags_ = tags_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.usage_ = usage_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.height_ = height_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto) {
          return mergeFrom((com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto other) {
        if (other == com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasPhotoId()) {
          setPhotoId(other.getPhotoId());
        }
        if (other.hasUserPhotoId()) {
          setUserPhotoId(other.getUserPhotoId());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
        if (other.hasUsage()) {
          setUsage(other.getUsage());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUrl()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              photoId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userPhotoId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              url_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              name_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              createDate_ = input.readInt32();
              break;
            }
            case 58: {
              ensureTagsIsMutable();
              tags_.add(input.readBytes());
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              usage_ = input.readInt32();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              width_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              height_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string userId = 1;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
      }
      
      // optional string photoId = 2;
      private java.lang.Object photoId_ = "";
      public boolean hasPhotoId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPhotoId() {
        java.lang.Object ref = photoId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          photoId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhotoId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        photoId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhotoId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        photoId_ = getDefaultInstance().getPhotoId();
        onChanged();
        return this;
      }
      void setPhotoId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        photoId_ = value;
        onChanged();
      }
      
      // optional string userPhotoId = 3;
      private java.lang.Object userPhotoId_ = "";
      public boolean hasUserPhotoId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getUserPhotoId() {
        java.lang.Object ref = userPhotoId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userPhotoId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserPhotoId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userPhotoId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserPhotoId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userPhotoId_ = getDefaultInstance().getUserPhotoId();
        onChanged();
        return this;
      }
      void setUserPhotoId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        userPhotoId_ = value;
        onChanged();
      }
      
      // required string url = 4;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        url_ = value;
        onChanged();
      }
      
      // optional string name = 5;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
      }
      
      // optional int32 createDate = 6;
      private int createDate_ ;
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getCreateDate() {
        return createDate_;
      }
      public Builder setCreateDate(int value) {
        bitField0_ |= 0x00000020;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createDate_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string tags = 7;
      private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
          bitField0_ |= 0x00000040;
         }
      }
      public java.util.List<String>
          getTagsList() {
        return java.util.Collections.unmodifiableList(tags_);
      }
      public int getTagsCount() {
        return tags_.size();
      }
      public String getTags(int index) {
        return tags_.get(index);
      }
      public Builder setTags(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addTags(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllTags(
          java.lang.Iterable<String> values) {
        ensureTagsIsMutable();
        super.addAll(values, tags_);
        onChanged();
        return this;
      }
      public Builder clearTags() {
        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      void addTags(com.google.protobuf.ByteString value) {
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
      }
      
      // optional int32 usage = 8;
      private int usage_ ;
      public boolean hasUsage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getUsage() {
        return usage_;
      }
      public Builder setUsage(int value) {
        bitField0_ |= 0x00000080;
        usage_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        usage_ = 0;
        onChanged();
        return this;
      }
      
      // optional float width = 9;
      private float width_ ;
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public float getWidth() {
        return width_;
      }
      public Builder setWidth(float value) {
        bitField0_ |= 0x00000100;
        width_ = value;
        onChanged();
        return this;
      }
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000100);
        width_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float height = 10;
      private float height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public float getHeight() {
        return height_;
      }
      public Builder setHeight(float value) {
        bitField0_ |= 0x00000200;
        height_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000200);
        height_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:game.PBUserPhoto)
    }
    
    static {
      defaultInstance = new PBUserPhoto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.PBUserPhoto)
  }
  
  public interface PBUserPhotoListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string userId = 1;
    boolean hasUserId();
    String getUserId();
    
    // repeated .game.PBUserPhoto photoList = 2;
    java.util.List<com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto> 
        getPhotoListList();
    com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto getPhotoList(int index);
    int getPhotoListCount();
    java.util.List<? extends com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder> 
        getPhotoListOrBuilderList();
    com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder getPhotoListOrBuilder(
        int index);
  }
  public static final class PBUserPhotoList extends
      com.google.protobuf.GeneratedMessage
      implements PBUserPhotoListOrBuilder {
    // Use PBUserPhotoList.newBuilder() to construct.
    private PBUserPhotoList(Builder builder) {
      super(builder);
    }
    private PBUserPhotoList(boolean noInit) {}
    
    private static final PBUserPhotoList defaultInstance;
    public static PBUserPhotoList getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBUserPhotoList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.PhotoProtos.internal_static_game_PBUserPhotoList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.model.PhotoProtos.internal_static_game_PBUserPhotoList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .game.PBUserPhoto photoList = 2;
    public static final int PHOTOLIST_FIELD_NUMBER = 2;
    private java.util.List<com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto> photoList_;
    public java.util.List<com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto> getPhotoListList() {
      return photoList_;
    }
    public java.util.List<? extends com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder> 
        getPhotoListOrBuilderList() {
      return photoList_;
    }
    public int getPhotoListCount() {
      return photoList_.size();
    }
    public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto getPhotoList(int index) {
      return photoList_.get(index);
    }
    public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder getPhotoListOrBuilder(
        int index) {
      return photoList_.get(index);
    }
    
    private void initFields() {
      userId_ = "";
      photoList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPhotoListCount(); i++) {
        if (!getPhotoList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      for (int i = 0; i < photoList_.size(); i++) {
        output.writeMessage(2, photoList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      for (int i = 0; i < photoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, photoList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.model.PhotoProtos.internal_static_game_PBUserPhotoList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.model.PhotoProtos.internal_static_game_PBUserPhotoList_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhotoListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (photoListBuilder_ == null) {
          photoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          photoListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList.getDescriptor();
      }
      
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList getDefaultInstanceForType() {
        return com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList build() {
        com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList buildPartial() {
        com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList result = new com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (photoListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            photoList_ = java.util.Collections.unmodifiableList(photoList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.photoList_ = photoList_;
        } else {
          result.photoList_ = photoListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList) {
          return mergeFrom((com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList other) {
        if (other == com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (photoListBuilder_ == null) {
          if (!other.photoList_.isEmpty()) {
            if (photoList_.isEmpty()) {
              photoList_ = other.photoList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePhotoListIsMutable();
              photoList_.addAll(other.photoList_);
            }
            onChanged();
          }
        } else {
          if (!other.photoList_.isEmpty()) {
            if (photoListBuilder_.isEmpty()) {
              photoListBuilder_.dispose();
              photoListBuilder_ = null;
              photoList_ = other.photoList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              photoListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhotoListFieldBuilder() : null;
            } else {
              photoListBuilder_.addAllMessages(other.photoList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        for (int i = 0; i < getPhotoListCount(); i++) {
          if (!getPhotoList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder subBuilder = com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPhotoList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string userId = 1;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
      }
      
      // repeated .game.PBUserPhoto photoList = 2;
      private java.util.List<com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto> photoList_ =
        java.util.Collections.emptyList();
      private void ensurePhotoListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          photoList_ = new java.util.ArrayList<com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto>(photoList_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder> photoListBuilder_;
      
      public java.util.List<com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto> getPhotoListList() {
        if (photoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(photoList_);
        } else {
          return photoListBuilder_.getMessageList();
        }
      }
      public int getPhotoListCount() {
        if (photoListBuilder_ == null) {
          return photoList_.size();
        } else {
          return photoListBuilder_.getCount();
        }
      }
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto getPhotoList(int index) {
        if (photoListBuilder_ == null) {
          return photoList_.get(index);
        } else {
          return photoListBuilder_.getMessage(index);
        }
      }
      public Builder setPhotoList(
          int index, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto value) {
        if (photoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotoListIsMutable();
          photoList_.set(index, value);
          onChanged();
        } else {
          photoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPhotoList(
          int index, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder builderForValue) {
        if (photoListBuilder_ == null) {
          ensurePhotoListIsMutable();
          photoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          photoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPhotoList(com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto value) {
        if (photoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotoListIsMutable();
          photoList_.add(value);
          onChanged();
        } else {
          photoListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPhotoList(
          int index, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto value) {
        if (photoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotoListIsMutable();
          photoList_.add(index, value);
          onChanged();
        } else {
          photoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPhotoList(
          com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder builderForValue) {
        if (photoListBuilder_ == null) {
          ensurePhotoListIsMutable();
          photoList_.add(builderForValue.build());
          onChanged();
        } else {
          photoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPhotoList(
          int index, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder builderForValue) {
        if (photoListBuilder_ == null) {
          ensurePhotoListIsMutable();
          photoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          photoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPhotoList(
          java.lang.Iterable<? extends com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto> values) {
        if (photoListBuilder_ == null) {
          ensurePhotoListIsMutable();
          super.addAll(values, photoList_);
          onChanged();
        } else {
          photoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPhotoList() {
        if (photoListBuilder_ == null) {
          photoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          photoListBuilder_.clear();
        }
        return this;
      }
      public Builder removePhotoList(int index) {
        if (photoListBuilder_ == null) {
          ensurePhotoListIsMutable();
          photoList_.remove(index);
          onChanged();
        } else {
          photoListBuilder_.remove(index);
        }
        return this;
      }
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder getPhotoListBuilder(
          int index) {
        return getPhotoListFieldBuilder().getBuilder(index);
      }
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder getPhotoListOrBuilder(
          int index) {
        if (photoListBuilder_ == null) {
          return photoList_.get(index);  } else {
          return photoListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder> 
           getPhotoListOrBuilderList() {
        if (photoListBuilder_ != null) {
          return photoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(photoList_);
        }
      }
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder addPhotoListBuilder() {
        return getPhotoListFieldBuilder().addBuilder(
            com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.getDefaultInstance());
      }
      public com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder addPhotoListBuilder(
          int index) {
        return getPhotoListFieldBuilder().addBuilder(
            index, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.getDefaultInstance());
      }
      public java.util.List<com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder> 
           getPhotoListBuilderList() {
        return getPhotoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder> 
          getPhotoListFieldBuilder() {
        if (photoListBuilder_ == null) {
          photoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder, com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoOrBuilder>(
                  photoList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          photoList_ = null;
        }
        return photoListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:game.PBUserPhotoList)
    }
    
    static {
      defaultInstance = new PBUserPhotoList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.PBUserPhotoList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_PBUserPhoto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_PBUserPhoto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_PBUserPhotoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_PBUserPhotoList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Photo.proto\022\004game\032\017GameBasic.proto\"\256\001\n" +
      "\013PBUserPhoto\022\016\n\006userId\030\001 \001(\t\022\017\n\007photoId\030" +
      "\002 \001(\t\022\023\n\013userPhotoId\030\003 \001(\t\022\013\n\003url\030\004 \002(\t\022" +
      "\014\n\004name\030\005 \001(\t\022\022\n\ncreateDate\030\006 \001(\005\022\014\n\004tag" +
      "s\030\007 \003(\t\022\r\n\005usage\030\010 \001(\005\022\r\n\005width\030\t \001(\002\022\016\n" +
      "\006height\030\n \001(\002\"G\n\017PBUserPhotoList\022\016\n\006user" +
      "Id\030\001 \002(\t\022$\n\tphotoList\030\002 \003(\0132\021.game.PBUse" +
      "rPhoto*<\n\014PBPhotoUsage\022\t\n\005BEGIN\020\000\022\014\n\010FOR" +
      "_DRAW\020\001\022\n\n\006FOR_PS\020\002\022\007\n\003END\020\003B5\n&com.oran" +
      "ge.network.game.protocol.modelB\013PhotoPro",
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_game_PBUserPhoto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_game_PBUserPhoto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_PBUserPhoto_descriptor,
              new java.lang.String[] { "UserId", "PhotoId", "UserPhotoId", "Url", "Name", "CreateDate", "Tags", "Usage", "Width", "Height", },
              com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.class,
              com.orange.network.game.protocol.model.PhotoProtos.PBUserPhoto.Builder.class);
          internal_static_game_PBUserPhotoList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_game_PBUserPhotoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_PBUserPhotoList_descriptor,
              new java.lang.String[] { "UserId", "PhotoList", },
              com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList.class,
              com.orange.network.game.protocol.model.PhotoProtos.PBUserPhotoList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.orange.network.game.protocol.model.GameBasicProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
