// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.orange.protocol.message;

public final class CommonProtos {
  private CommonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBDeviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:barrage.PBDevice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * refer to PBDeviceType
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * refer to PBDeviceType
     * </pre>
     */
    int getType();

    /**
     * <code>optional string model = 2;</code>
     */
    boolean hasModel();
    /**
     * <code>optional string model = 2;</code>
     */
    java.lang.String getModel();
    /**
     * <code>optional string model = 2;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>optional string os = 3;</code>
     */
    boolean hasOs();
    /**
     * <code>optional string os = 3;</code>
     */
    java.lang.String getOs();
    /**
     * <code>optional string os = 3;</code>
     */
    com.google.protobuf.ByteString
        getOsBytes();

    /**
     * <code>optional string deviceId = 4;</code>
     *
     * <pre>
     * for iPhone
     * </pre>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string deviceId = 4;</code>
     *
     * <pre>
     * for iPhone
     * </pre>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string deviceId = 4;</code>
     *
     * <pre>
     * for iPhone
     * </pre>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>optional string deviceToken = 5;</code>
     */
    boolean hasDeviceToken();
    /**
     * <code>optional string deviceToken = 5;</code>
     */
    java.lang.String getDeviceToken();
    /**
     * <code>optional string deviceToken = 5;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTokenBytes();

    /**
     * <code>optional bool isJailBroken = 6;</code>
     */
    boolean hasIsJailBroken();
    /**
     * <code>optional bool isJailBroken = 6;</code>
     */
    boolean getIsJailBroken();
  }
  /**
   * Protobuf type {@code barrage.PBDevice}
   */
  public static final class PBDevice extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:barrage.PBDevice)
      PBDeviceOrBuilder {
    // Use PBDevice.newBuilder() to construct.
    private PBDevice(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBDevice(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBDevice defaultInstance;
    public static PBDevice getDefaultInstance() {
      return defaultInstance;
    }

    public PBDevice getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBDevice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              model_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              os_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              deviceId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              deviceToken_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              isJailBroken_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBDevice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orange.protocol.message.CommonProtos.PBDevice.class, com.orange.protocol.message.CommonProtos.PBDevice.Builder.class);
    }

    public static com.google.protobuf.Parser<PBDevice> PARSER =
        new com.google.protobuf.AbstractParser<PBDevice>() {
      public PBDevice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBDevice(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBDevice> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * refer to PBDeviceType
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * refer to PBDeviceType
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int MODEL_FIELD_NUMBER = 2;
    private java.lang.Object model_;
    /**
     * <code>optional string model = 2;</code>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string model = 2;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          model_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string model = 2;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OS_FIELD_NUMBER = 3;
    private java.lang.Object os_;
    /**
     * <code>optional string os = 3;</code>
     */
    public boolean hasOs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string os = 3;</code>
     */
    public java.lang.String getOs() {
      java.lang.Object ref = os_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          os_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string os = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEID_FIELD_NUMBER = 4;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string deviceId = 4;</code>
     *
     * <pre>
     * for iPhone
     * </pre>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string deviceId = 4;</code>
     *
     * <pre>
     * for iPhone
     * </pre>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceId = 4;</code>
     *
     * <pre>
     * for iPhone
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICETOKEN_FIELD_NUMBER = 5;
    private java.lang.Object deviceToken_;
    /**
     * <code>optional string deviceToken = 5;</code>
     */
    public boolean hasDeviceToken() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string deviceToken = 5;</code>
     */
    public java.lang.String getDeviceToken() {
      java.lang.Object ref = deviceToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceToken = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTokenBytes() {
      java.lang.Object ref = deviceToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISJAILBROKEN_FIELD_NUMBER = 6;
    private boolean isJailBroken_;
    /**
     * <code>optional bool isJailBroken = 6;</code>
     */
    public boolean hasIsJailBroken() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool isJailBroken = 6;</code>
     */
    public boolean getIsJailBroken() {
      return isJailBroken_;
    }

    private void initFields() {
      type_ = 0;
      model_ = "";
      os_ = "";
      deviceId_ = "";
      deviceToken_ = "";
      isJailBroken_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getModelBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getOsBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDeviceTokenBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, isJailBroken_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getModelBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOsBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDeviceTokenBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isJailBroken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.orange.protocol.message.CommonProtos.PBDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.protocol.message.CommonProtos.PBDevice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code barrage.PBDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:barrage.PBDevice)
        com.orange.protocol.message.CommonProtos.PBDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBDevice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orange.protocol.message.CommonProtos.PBDevice.class, com.orange.protocol.message.CommonProtos.PBDevice.Builder.class);
      }

      // Construct using com.orange.protocol.message.CommonProtos.PBDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        model_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        os_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        isJailBroken_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBDevice_descriptor;
      }

      public com.orange.protocol.message.CommonProtos.PBDevice getDefaultInstanceForType() {
        return com.orange.protocol.message.CommonProtos.PBDevice.getDefaultInstance();
      }

      public com.orange.protocol.message.CommonProtos.PBDevice build() {
        com.orange.protocol.message.CommonProtos.PBDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orange.protocol.message.CommonProtos.PBDevice buildPartial() {
        com.orange.protocol.message.CommonProtos.PBDevice result = new com.orange.protocol.message.CommonProtos.PBDevice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.os_ = os_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceToken_ = deviceToken_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isJailBroken_ = isJailBroken_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.protocol.message.CommonProtos.PBDevice) {
          return mergeFrom((com.orange.protocol.message.CommonProtos.PBDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orange.protocol.message.CommonProtos.PBDevice other) {
        if (other == com.orange.protocol.message.CommonProtos.PBDevice.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasModel()) {
          bitField0_ |= 0x00000002;
          model_ = other.model_;
          onChanged();
        }
        if (other.hasOs()) {
          bitField0_ |= 0x00000004;
          os_ = other.os_;
          onChanged();
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000008;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasDeviceToken()) {
          bitField0_ |= 0x00000010;
          deviceToken_ = other.deviceToken_;
          onChanged();
        }
        if (other.hasIsJailBroken()) {
          setIsJailBroken(other.getIsJailBroken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orange.protocol.message.CommonProtos.PBDevice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orange.protocol.message.CommonProtos.PBDevice) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * refer to PBDeviceType
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * refer to PBDeviceType
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * refer to PBDeviceType
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * refer to PBDeviceType
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>optional string model = 2;</code>
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string model = 2;</code>
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            model_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string model = 2;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string model = 2;</code>
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string model = 2;</code>
       */
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string model = 2;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        model_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object os_ = "";
      /**
       * <code>optional string os = 3;</code>
       */
      public boolean hasOs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string os = 3;</code>
       */
      public java.lang.String getOs() {
        java.lang.Object ref = os_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            os_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string os = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOsBytes() {
        java.lang.Object ref = os_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          os_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string os = 3;</code>
       */
      public Builder setOs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        os_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string os = 3;</code>
       */
      public Builder clearOs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        os_ = getDefaultInstance().getOs();
        onChanged();
        return this;
      }
      /**
       * <code>optional string os = 3;</code>
       */
      public Builder setOsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        os_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string deviceId = 4;</code>
       *
       * <pre>
       * for iPhone
       * </pre>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string deviceId = 4;</code>
       *
       * <pre>
       * for iPhone
       * </pre>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceId = 4;</code>
       *
       * <pre>
       * for iPhone
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceId = 4;</code>
       *
       * <pre>
       * for iPhone
       * </pre>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 4;</code>
       *
       * <pre>
       * for iPhone
       * </pre>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 4;</code>
       *
       * <pre>
       * for iPhone
       * </pre>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceToken_ = "";
      /**
       * <code>optional string deviceToken = 5;</code>
       */
      public boolean hasDeviceToken() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string deviceToken = 5;</code>
       */
      public java.lang.String getDeviceToken() {
        java.lang.Object ref = deviceToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceToken_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceToken = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTokenBytes() {
        java.lang.Object ref = deviceToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceToken = 5;</code>
       */
      public Builder setDeviceToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceToken = 5;</code>
       */
      public Builder clearDeviceToken() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceToken_ = getDefaultInstance().getDeviceToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceToken = 5;</code>
       */
      public Builder setDeviceTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceToken_ = value;
        onChanged();
        return this;
      }

      private boolean isJailBroken_ ;
      /**
       * <code>optional bool isJailBroken = 6;</code>
       */
      public boolean hasIsJailBroken() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool isJailBroken = 6;</code>
       */
      public boolean getIsJailBroken() {
        return isJailBroken_;
      }
      /**
       * <code>optional bool isJailBroken = 6;</code>
       */
      public Builder setIsJailBroken(boolean value) {
        bitField0_ |= 0x00000020;
        isJailBroken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isJailBroken = 6;</code>
       */
      public Builder clearIsJailBroken() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isJailBroken_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:barrage.PBDevice)
    }

    static {
      defaultInstance = new PBDevice(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:barrage.PBDevice)
  }

  public interface PBPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:barrage.PBPoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 posX = 1;</code>
     */
    boolean hasPosX();
    /**
     * <code>optional int32 posX = 1;</code>
     */
    int getPosX();

    /**
     * <code>optional int32 poxY = 2;</code>
     */
    boolean hasPoxY();
    /**
     * <code>optional int32 poxY = 2;</code>
     */
    int getPoxY();
  }
  /**
   * Protobuf type {@code barrage.PBPoint}
   */
  public static final class PBPoint extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:barrage.PBPoint)
      PBPointOrBuilder {
    // Use PBPoint.newBuilder() to construct.
    private PBPoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBPoint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBPoint defaultInstance;
    public static PBPoint getDefaultInstance() {
      return defaultInstance;
    }

    public PBPoint getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              posX_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              poxY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPoint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orange.protocol.message.CommonProtos.PBPoint.class, com.orange.protocol.message.CommonProtos.PBPoint.Builder.class);
    }

    public static com.google.protobuf.Parser<PBPoint> PARSER =
        new com.google.protobuf.AbstractParser<PBPoint>() {
      public PBPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBPoint(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBPoint> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int POSX_FIELD_NUMBER = 1;
    private int posX_;
    /**
     * <code>optional int32 posX = 1;</code>
     */
    public boolean hasPosX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 posX = 1;</code>
     */
    public int getPosX() {
      return posX_;
    }

    public static final int POXY_FIELD_NUMBER = 2;
    private int poxY_;
    /**
     * <code>optional int32 poxY = 2;</code>
     */
    public boolean hasPoxY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 poxY = 2;</code>
     */
    public int getPoxY() {
      return poxY_;
    }

    private void initFields() {
      posX_ = 0;
      poxY_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, posX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, poxY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, posX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, poxY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.orange.protocol.message.CommonProtos.PBPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.protocol.message.CommonProtos.PBPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code barrage.PBPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:barrage.PBPoint)
        com.orange.protocol.message.CommonProtos.PBPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPoint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orange.protocol.message.CommonProtos.PBPoint.class, com.orange.protocol.message.CommonProtos.PBPoint.Builder.class);
      }

      // Construct using com.orange.protocol.message.CommonProtos.PBPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        posX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        poxY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPoint_descriptor;
      }

      public com.orange.protocol.message.CommonProtos.PBPoint getDefaultInstanceForType() {
        return com.orange.protocol.message.CommonProtos.PBPoint.getDefaultInstance();
      }

      public com.orange.protocol.message.CommonProtos.PBPoint build() {
        com.orange.protocol.message.CommonProtos.PBPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orange.protocol.message.CommonProtos.PBPoint buildPartial() {
        com.orange.protocol.message.CommonProtos.PBPoint result = new com.orange.protocol.message.CommonProtos.PBPoint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.posX_ = posX_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.poxY_ = poxY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.protocol.message.CommonProtos.PBPoint) {
          return mergeFrom((com.orange.protocol.message.CommonProtos.PBPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orange.protocol.message.CommonProtos.PBPoint other) {
        if (other == com.orange.protocol.message.CommonProtos.PBPoint.getDefaultInstance()) return this;
        if (other.hasPosX()) {
          setPosX(other.getPosX());
        }
        if (other.hasPoxY()) {
          setPoxY(other.getPoxY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orange.protocol.message.CommonProtos.PBPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orange.protocol.message.CommonProtos.PBPoint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int posX_ ;
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public int getPosX() {
        return posX_;
      }
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public Builder setPosX(int value) {
        bitField0_ |= 0x00000001;
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        posX_ = 0;
        onChanged();
        return this;
      }

      private int poxY_ ;
      /**
       * <code>optional int32 poxY = 2;</code>
       */
      public boolean hasPoxY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 poxY = 2;</code>
       */
      public int getPoxY() {
        return poxY_;
      }
      /**
       * <code>optional int32 poxY = 2;</code>
       */
      public Builder setPoxY(int value) {
        bitField0_ |= 0x00000002;
        poxY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 poxY = 2;</code>
       */
      public Builder clearPoxY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        poxY_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:barrage.PBPoint)
    }

    static {
      defaultInstance = new PBPoint(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:barrage.PBPoint)
  }

  public interface PBPointListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:barrage.PBPointList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    java.util.List<com.orange.protocol.message.CommonProtos.PBPoint> 
        getPointList();
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    com.orange.protocol.message.CommonProtos.PBPoint getPoint(int index);
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    int getPointCount();
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    java.util.List<? extends com.orange.protocol.message.CommonProtos.PBPointOrBuilder> 
        getPointOrBuilderList();
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    com.orange.protocol.message.CommonProtos.PBPointOrBuilder getPointOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code barrage.PBPointList}
   */
  public static final class PBPointList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:barrage.PBPointList)
      PBPointListOrBuilder {
    // Use PBPointList.newBuilder() to construct.
    private PBPointList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBPointList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBPointList defaultInstance;
    public static PBPointList getDefaultInstance() {
      return defaultInstance;
    }

    public PBPointList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBPointList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                point_ = new java.util.ArrayList<com.orange.protocol.message.CommonProtos.PBPoint>();
                mutable_bitField0_ |= 0x00000001;
              }
              point_.add(input.readMessage(com.orange.protocol.message.CommonProtos.PBPoint.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          point_ = java.util.Collections.unmodifiableList(point_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPointList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPointList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orange.protocol.message.CommonProtos.PBPointList.class, com.orange.protocol.message.CommonProtos.PBPointList.Builder.class);
    }

    public static com.google.protobuf.Parser<PBPointList> PARSER =
        new com.google.protobuf.AbstractParser<PBPointList>() {
      public PBPointList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBPointList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBPointList> getParserForType() {
      return PARSER;
    }

    public static final int POINT_FIELD_NUMBER = 1;
    private java.util.List<com.orange.protocol.message.CommonProtos.PBPoint> point_;
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    public java.util.List<com.orange.protocol.message.CommonProtos.PBPoint> getPointList() {
      return point_;
    }
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    public java.util.List<? extends com.orange.protocol.message.CommonProtos.PBPointOrBuilder> 
        getPointOrBuilderList() {
      return point_;
    }
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    public int getPointCount() {
      return point_.size();
    }
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    public com.orange.protocol.message.CommonProtos.PBPoint getPoint(int index) {
      return point_.get(index);
    }
    /**
     * <code>repeated .barrage.PBPoint point = 1;</code>
     */
    public com.orange.protocol.message.CommonProtos.PBPointOrBuilder getPointOrBuilder(
        int index) {
      return point_.get(index);
    }

    private void initFields() {
      point_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < point_.size(); i++) {
        output.writeMessage(1, point_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < point_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, point_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.orange.protocol.message.CommonProtos.PBPointList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.CommonProtos.PBPointList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.protocol.message.CommonProtos.PBPointList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code barrage.PBPointList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:barrage.PBPointList)
        com.orange.protocol.message.CommonProtos.PBPointListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPointList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPointList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orange.protocol.message.CommonProtos.PBPointList.class, com.orange.protocol.message.CommonProtos.PBPointList.Builder.class);
      }

      // Construct using com.orange.protocol.message.CommonProtos.PBPointList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPointFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pointBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.protocol.message.CommonProtos.internal_static_barrage_PBPointList_descriptor;
      }

      public com.orange.protocol.message.CommonProtos.PBPointList getDefaultInstanceForType() {
        return com.orange.protocol.message.CommonProtos.PBPointList.getDefaultInstance();
      }

      public com.orange.protocol.message.CommonProtos.PBPointList build() {
        com.orange.protocol.message.CommonProtos.PBPointList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orange.protocol.message.CommonProtos.PBPointList buildPartial() {
        com.orange.protocol.message.CommonProtos.PBPointList result = new com.orange.protocol.message.CommonProtos.PBPointList(this);
        int from_bitField0_ = bitField0_;
        if (pointBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            point_ = java.util.Collections.unmodifiableList(point_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.point_ = point_;
        } else {
          result.point_ = pointBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.protocol.message.CommonProtos.PBPointList) {
          return mergeFrom((com.orange.protocol.message.CommonProtos.PBPointList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orange.protocol.message.CommonProtos.PBPointList other) {
        if (other == com.orange.protocol.message.CommonProtos.PBPointList.getDefaultInstance()) return this;
        if (pointBuilder_ == null) {
          if (!other.point_.isEmpty()) {
            if (point_.isEmpty()) {
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePointIsMutable();
              point_.addAll(other.point_);
            }
            onChanged();
          }
        } else {
          if (!other.point_.isEmpty()) {
            if (pointBuilder_.isEmpty()) {
              pointBuilder_.dispose();
              pointBuilder_ = null;
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pointBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPointFieldBuilder() : null;
            } else {
              pointBuilder_.addAllMessages(other.point_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orange.protocol.message.CommonProtos.PBPointList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orange.protocol.message.CommonProtos.PBPointList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.orange.protocol.message.CommonProtos.PBPoint> point_ =
        java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          point_ = new java.util.ArrayList<com.orange.protocol.message.CommonProtos.PBPoint>(point_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.orange.protocol.message.CommonProtos.PBPoint, com.orange.protocol.message.CommonProtos.PBPoint.Builder, com.orange.protocol.message.CommonProtos.PBPointOrBuilder> pointBuilder_;

      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public java.util.List<com.orange.protocol.message.CommonProtos.PBPoint> getPointList() {
        if (pointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(point_);
        } else {
          return pointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public int getPointCount() {
        if (pointBuilder_ == null) {
          return point_.size();
        } else {
          return pointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public com.orange.protocol.message.CommonProtos.PBPoint getPoint(int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);
        } else {
          return pointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder setPoint(
          int index, com.orange.protocol.message.CommonProtos.PBPoint value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.set(index, value);
          onChanged();
        } else {
          pointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder setPoint(
          int index, com.orange.protocol.message.CommonProtos.PBPoint.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder addPoint(com.orange.protocol.message.CommonProtos.PBPoint value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(value);
          onChanged();
        } else {
          pointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder addPoint(
          int index, com.orange.protocol.message.CommonProtos.PBPoint value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(index, value);
          onChanged();
        } else {
          pointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder addPoint(
          com.orange.protocol.message.CommonProtos.PBPoint.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder addPoint(
          int index, com.orange.protocol.message.CommonProtos.PBPoint.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder addAllPoint(
          java.lang.Iterable<? extends com.orange.protocol.message.CommonProtos.PBPoint> values) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, point_);
          onChanged();
        } else {
          pointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder clearPoint() {
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public Builder removePoint(int index) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.remove(index);
          onChanged();
        } else {
          pointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public com.orange.protocol.message.CommonProtos.PBPoint.Builder getPointBuilder(
          int index) {
        return getPointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public com.orange.protocol.message.CommonProtos.PBPointOrBuilder getPointOrBuilder(
          int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);  } else {
          return pointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public java.util.List<? extends com.orange.protocol.message.CommonProtos.PBPointOrBuilder> 
           getPointOrBuilderList() {
        if (pointBuilder_ != null) {
          return pointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(point_);
        }
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public com.orange.protocol.message.CommonProtos.PBPoint.Builder addPointBuilder() {
        return getPointFieldBuilder().addBuilder(
            com.orange.protocol.message.CommonProtos.PBPoint.getDefaultInstance());
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public com.orange.protocol.message.CommonProtos.PBPoint.Builder addPointBuilder(
          int index) {
        return getPointFieldBuilder().addBuilder(
            index, com.orange.protocol.message.CommonProtos.PBPoint.getDefaultInstance());
      }
      /**
       * <code>repeated .barrage.PBPoint point = 1;</code>
       */
      public java.util.List<com.orange.protocol.message.CommonProtos.PBPoint.Builder> 
           getPointBuilderList() {
        return getPointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.orange.protocol.message.CommonProtos.PBPoint, com.orange.protocol.message.CommonProtos.PBPoint.Builder, com.orange.protocol.message.CommonProtos.PBPointOrBuilder> 
          getPointFieldBuilder() {
        if (pointBuilder_ == null) {
          pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.orange.protocol.message.CommonProtos.PBPoint, com.orange.protocol.message.CommonProtos.PBPoint.Builder, com.orange.protocol.message.CommonProtos.PBPointOrBuilder>(
                  point_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          point_ = null;
        }
        return pointBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:barrage.PBPointList)
    }

    static {
      defaultInstance = new PBPointList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:barrage.PBPointList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_barrage_PBDevice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_barrage_PBDevice_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_barrage_PBPoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_barrage_PBPoint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_barrage_PBPointList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_barrage_PBPointList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\022\007barrage\"p\n\010PBDevice\022\014\n\004t" +
      "ype\030\001 \002(\005\022\r\n\005model\030\002 \001(\t\022\n\n\002os\030\003 \001(\t\022\020\n\010" +
      "deviceId\030\004 \001(\t\022\023\n\013deviceToken\030\005 \001(\t\022\024\n\014i" +
      "sJailBroken\030\006 \001(\010\"%\n\007PBPoint\022\014\n\004posX\030\001 \001" +
      "(\005\022\014\n\004poxY\030\002 \001(\005\".\n\013PBPointList\022\037\n\005point" +
      "\030\001 \003(\0132\020.barrage.PBPointB+\n\033com.orange.p" +
      "rotocol.messageB\014CommonProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_barrage_PBDevice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_barrage_PBDevice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_barrage_PBDevice_descriptor,
        new java.lang.String[] { "Type", "Model", "Os", "DeviceId", "DeviceToken", "IsJailBroken", });
    internal_static_barrage_PBPoint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_barrage_PBPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_barrage_PBPoint_descriptor,
        new java.lang.String[] { "PosX", "PoxY", });
    internal_static_barrage_PBPointList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_barrage_PBPointList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_barrage_PBPointList_descriptor,
        new java.lang.String[] { "Point", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
