package com.orange.game.traffic.robot.client;

public class RobotNickName {

	public final static String[]  MALE_NICK_NAME = {
		"Jacob", "Ethan", "Michael", "Alexander", "William", 
		"Joshua", "Daniel", "Jayden", "Noah", "Anthony",
		"Christopher", "Aiden", "Matthew", "David", "Andrew",
		"Joseph", "Logan", "James", "Ryan", "Benjamin", 
		"Elijah", "Gabriel", "Christian", "Nathan", "Jackson",
		"John", "Samuel", "Tyler", "Dylan", "Jonathan",
		"Caleb", "Nicholas", "Gavin", "Mason", "Evan", 
		"Landon", "Angel", "Brandon", "Lucas", "Isaac", 
		"Diego", "Nathaniel", "Brody", "Jesus", "Carlos",
		"Tristan", "Dominic", "Cole", "Alex", "Cooper",
		"Ayden", "Carson", "Josiah", "Levi", "Blake", 
		"Eli", "Hayden", "Bryan", "Colton", "Brian",
		"Eric", "Parker", "Sean", "Oliver", "Miguel",  
		"Jayden", "Gabriella", "Thomas", "Cameron", "Connor",
		"少从秋","孤草","我还只是一个孩纸","逆戟鲸","老严","卜青柏",
		"御草堂","冰釋★☆訧","椭吮涨咨吵","逑の娭毑","伊凡",
		"谶纬","独钓寒江雪_-","独钓寒江雪_-","帅哥","野狼",
		"左曼荷","不败 *皇朝 ","寂寞人生","维宝","陈世美",
		"〆洪门↘太子","指间烟云","看你演","高原雄鹰","拼出个未来",
		"虚竹","我們正眼看過誰","火云邪神","眺望者。","滑稽取宠",
		"为谁的颜憔悴", "强颜欢" , "壞人" ,"心系Ｄ3少年郎", "莫名的丶寂寞",
        "習慣成型", "十字路口的?殤" ,"╯記憶裏只有沵", "奢侈安玍" , "迷茫",
        "自卑的、青春", "晨①逅", "所谓Dé懓情", "-流逝", "淡藍↙愛",
        "點莫，半柱香" , "未︴命名", "戲劇╮", "彼此的承諾、","斜对角的苍白",
        "寒江雪", "★★★★★", "单 身 中","超越梦乡","释摩",
        "飞沙", "快乐大男孩","回乡的人","使命","沉睡的冰",
        "無sex手機通訊","憨哥", "无名指的等", "分不清的梦找不到边的情","我不快乐",
        "幽蓝心境", "旭峰家居", "三十大男孩","永不言败", "穷人一个",
        "好男", "绿地骏马", "话剧-人生", "我是莫言", "999年老二",
        "霸王枪", "彭哥", "赌王","蜥蜴眼中肉","光辉岁月",
	};
	
	public final static String[] FEMALE_NICK_NAME = {
		"Isabella", "Emma", "Olivia", "Sophia", "Ava",
		"Emily", "Madison", "Abigail","Chloe", "Mia",
		"Elizabeth", "Addison", "Alexis", "Ella", "Samantha",
		"Natalie", "Grace", "Lily", "Alyssa", "Ashley", 
		"Sarah", "Taylor", "Hannah", "Brianna", "Hailey",
		"Kaylee", "Lillian", "Leah", "Anna", "Allison",
		"Victoria", "Avery", "Gabriella", "Nevaeh", "Kayla", 
		"Sofia", "Brooklyn", "Riley", "Evelyn", "Savannah",
		"Aubrey", "Alexa", "Peyton", "Makayla", "Layla",
		"Lauren", "Zoe", "Sydney", "Audrey", "Julia", 
		"Jasmine", "Arianna", "Claire", "Brooke", "Amelia", 
		"Morgan", "Destiny", "Bella", "Madelyn", "Katherine",
		"Kylie", "Maya", "Aaliyah", "Madeline", "Sophie",
		"Kimberly", "Kaitlyn", "Charlotte", "Alexandra", "Jocelyn", 
		"似水飘洋", "&糊*涂&","晓寒","丶墨秋浅凉","触及不到你沧桑的容颜",
		"幸褔像花儿","冷若冰霜","草原玉女","落花，知惜","{觜角丄揚",
		"(_頖縌ゞ尐姊", "芙蓉一笑一倾城","时间走人在变","蓝色妖姬","平平淡淡才是真",
		"用任性隐藏被伤的xi","宁缺毋滥","半颗心love","红颜心已碎","老鼠爱大米",
		"可爱多","三叶草","缘来友你","5+5=ji","南卉",
		"光阴逝水","小孩","ミ草莓＼丫头","左边","寒塘野鹤",
		"嘘_别紧张", "骄傲的十五岁" ,"①岁就很乖" , "小小象 ﹌" ,"伱留下の丶只是伤",
        "若凌° Provence -", "ゞ情绪、莫名的纠結。", "へ都只是个孩子", "|▌时光会带走我们的回忆","若你爱我何以见得",
		"温暖最终遥远不过时光 °", "一颗芯，宁缺毋滥*/", "她的故事他的梦", "可不可以不坚强.","一个人安安静静就好°",
		"情已殇、如此寂寞~" , "悲恋时光回不到初始 =", "刻骨銘心", "青春就是白日发春/-", "看惯了我不愿看到的样子乀",
		"笑春涵菡紫南","?兒？童ミ","梦醒时分","余宛菡","小艺江春",
		"会微笑的兔子","放不下","紫岩星月","小龙女","╮左心房",
		"色女", "依琴采波","灰色的记忆","水美人","温柔一刀",
		"白衣天使","梦%思","煞笔陆琪","天空依然蓝","一辈子幸福",
		"你若有情", "人生如梦啊", "往事如烟","红玫","格格",
		"西山晴雪", "雨雾杉林","寒冰翠","梦然","我很丑",
	};
	
}
